### PR TITLE
removed port.h.patch as it is no longer needed

### PR DESCRIPTION
**Pull request by HarithaIBM**
The` if defined` block was added to include an header` #include <sys/endian.h>` in port.h file. This header is not present in port.h file in the latest stable build.

Hence, the patch was not applying and the build was failing. On removing this patch file, build is completed successfully.

### CODE REVIEW

**Comment by HarithaIBM** [comment]
Fix works with latest clang

**Comment by IgorTodorovskiIBM** [comment]
Tests passed, will merge

**Pull request merged**
